version: '3.8'

services:
  api:
    build: .
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=your_database_name
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    container_name: db-main
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=your_database_name
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database-data:/var/lib/mysql